[image]
art = "../samples/getting-started/img.jpg"
bg_color = "#54130CFF"
# image_height = 1490

[text]
text = "../samples/getting-started/text.txt"
text_box_pos = "split"
credits = ['Photo: Ryan Yao on Unsplash']
# base_font_height = 30
# padding = 1
# line_spacing = 0.200
# text_width = 29.440
# alignment = "center"
# credits_pos = "tl"

[output]
outputs = ['caption', 'autospec']
output_directory = "../samples/getting-started"
base_filename = "test"
# output_img_format = "png"
# output_img_quality = 100

[[characters]]
name = "serif"
color = "#F0C7C2FF"
font = "../fonts/Noto_Serif/NotoSerif-Regular.ttf"
# relative_height = 1
# stroke_width = 0
# stroke_color = "#000000FF"
# font_bold = "../fonts/Noto_Serif/NotoSerif-Bold.ttf"
# font_italic = "../fonts/Noto_Serif/NotoSerif-Italic.ttf"
# font_bolditalic = "../fonts/Noto_Serif/NotoSerif-BoldItalic.ttf"

[[characters]]
name = "sans"
color = "#C2EFF0FF"
relative_height = 0.700
font = "../fonts/Noto_Sans/NotoSans-Regular.ttf"
# stroke_width = 0
# stroke_color = "#000000FF"
# font_bold = "../fonts/Noto_Sans/NotoSans-Bold.ttf"
# font_italic = "../fonts/Noto_Sans/NotoSans-Italic.ttf"
# font_bolditalic = "../fonts/Noto_Sans/NotoSans-BoldItalic.ttf"

[[characters]]
name = "em"
color = "#FFFFFFFF"
font = "../fonts/Noto_Emoji/NotoEmoji-Regular.ttf"
# relative_height = 1
# stroke_width = 0
# stroke_color = "#000000FF"
# font_bold = "../fonts/Noto_Emoji/NotoEmoji-Bold.ttf"
# font_italic = "../fonts/Noto_Emoji/NotoEmoji-Regular.ttf"
# font_bolditalic = "../fonts/Noto_Emoji/NotoEmoji-Regular.ttf"

[[characters]]
name = "credits"
color = "#54130CFF"
relative_height = 0.700
font = "../fonts/Noto_Sans/NotoSans-Regular.ttf"
# stroke_width = 0
# stroke_color = "#000000FF"
# font_bold = "../fonts/Noto_Sans/NotoSans-Bold.ttf"
# font_italic = "../fonts/Noto_Sans/NotoSans-Italic.ttf"
# font_bolditalic = "../fonts/Noto_Sans/NotoSans-BoldItalic.ttf"

